# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - IDEA_VERSION: IC-2023.2.5
            JDK_VERSION: 17
          - IDEA_VERSION: IC-2024.1
            JDK_VERSION: 17
          - IDEA_VERSION: IU-LATEST-EAP-SNAPSHOT
            JDK_VERSION: 17

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        if: matrix.env.JDK_VERSION != '17'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Set up JDK 17
        if: matrix.env.JDK_VERSION == '17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Gradle
        run: |
          ./gradlew -PideaVersion=${IDEA_VERSION} check buildPlugin
        env: ${{ matrix.env }}
      - name: Archive distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: "intellij-haskell-lsp-development"
          path: build/distributions/intellij-haskell-lsp-*.zip
        if: matrix.env.IDEA_VERSION == 'IC-2023.2.5'
